language: ruby
rvm:
  - 2.1.0
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension if not exists hstore"
script:
  - RAILS_ENV=test bundle exec rake db:migrate 
  - RAILS_ENV=test bundle exec rake test:prepare
